# This is a basic workflow to help you get started with Actions

name: Build Gurt Clicker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Download LÖVE
      - name: Download LÖVE
        run: |
          wget https://github.com/love2d/love/releases/download/11.5/love-11.5-win32.zip
          unzip love-11.5-win32.zip

      # Zip Source Code excluding github leftovers.
      - name: Zip Source Code
        run: |
            zip -r GurtClicker.love . -x ".git/*" ".github/*" ".gitignore"  

      # Compile the love file to an executable
      - name: Compile to executable
        run: |
          cat love-11.5-win32/love.exe GurtClicker.love > GurtClicker.exe

      # Upload the love file as an artifact
      - name: Upload love file
        uses: actions/upload-artifact@v4
        with:
          name: GurtClicker.love
          path: GurtClicker.love

      # Upload the executable as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: GurtClicker.exe
          path: GurtClicker.exe

      # Create a release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
           GurtClicker.love
           GurtClicker.exe

